modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/Compressed-Chorus-Fruit/issues/new/choose"
[[mods]]
modId="compressedchorusfruit"
version="${file.jarVersion}"
displayName="Compressed Chorus Fruit"
displayURL="https://www.curseforge.com/minecraft/mc-mods/compressed-chorus-fruit"
logoFile="examplemod.png"
credits="Thanks for downloading this mod."
authors="YTrollman"
description="This mod adds a compressed Chorus Fruit."

[[dependencies.compressedchorusfruit]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.compressedchorusfruit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"